version: "2"
services:
    www:
        container_name: php
        image: apache2
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        networks:
            - default
volumes:
    persistent:
